### ISSUE TITLE
Backend routes

### ISSUE THREAD

**Issue by linakherchi** [AEDGitHub/CoffeeWithConfidants#3]
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

**Comment by AEDGitHub** [comment]
Lina,

I believe the CWC backend routes list to be complete for the time being, though certainly still a rough draft. I have many considerations (for you, Google, and/or my own personal reflections) on how to best optimize, and questions on whether or not I have written the routes incorrectly or non-optimally.

Also, as a heads up, the above link "superfluous routes" to https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md is reading as a 404.

R/S,
-Eric
