### ISSUE TITLE
Frontend routes

### ISSUE THREAD

**Issue by linakherchi** [AEDGitHub/CoffeeWithConfidants#4]
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by AEDGitHub** [comment]
Lina,

Of all the wiki sections so far, this is the one I'm most confused about. I believe the routes all meet the above criteria, however.

R/S,
-Eric
